version: '3.8'

services:
  app:
    build: ./.docker/node
    ports:
      - 8081:3000
    tty: true
    command: sh -c "sleep infinity"
    volumes:
      - ./:/app
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: estoque
      MYSQL_DATABASE: estoque
      MYSQL_USER: estoque
      MYSQL_PASSWORD: estoque
    ports:
      - "3307:3306"
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
    